language: python
python:
  - "3.8"
install:
  - pip install -r requirements.txt
script:
  - make publish
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  local_dir: output
  on:
    branch: master
